# SPDX-License-Identifier: BSD-2-Clause
name: rexce-snapshot-sign
on:
  workflow_dispatch: {}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo rexce-snapshot-sign
